import dynamic from 'next/dynamic'
import Head from 'next/head'
import Layout from '../components/Layout'
import Suggestions from '../components/Suggestions';
const Feed = dynamic(() => import('../components/Feed'));

export default function Home() {
  return (
    <div>
      <Head>
        <title>TikTok Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Feed />
        <Suggestions />
      </Layout>
    </div>
  )
}
